# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='created_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='message',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
