# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20170902_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=200)),
                ('created_time', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
