# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='message',
        ),
    ]
